In [4]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태: ',array1.shape)

array2 = np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태: ',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태: ',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
list1=[1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
list2 =[1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [3]:
#19페이지
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [5]:
#19페이지
sequence_array = np.arange(2,10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[2 3 4 5 6 7 8 9]
int64 (8,)


In [8]:
#19페이지
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one = np.ones((3,2))
print(one)
print(one.dtype, one.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
#20페이지
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape((5,2))
print('array3:\n', array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
#21페이지
array1.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [12]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(-1,5)
print('array2:\n', array2)
print(array2.shape)

array3 = array1.reshape(5,-1)
print('array3:\n', array3)
print(array3.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [13]:
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원을 2차원으로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape', array5.shape)

#1차원을 2차원으로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape (8, 1)


In [19]:
#1~9 1차원 배열 생성
array1 = np.arange(start=1, stop=10)
print(array1)

#index는 0부터 시작, array1[2]는 세번째 값
value = array1[2]
print(value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int64'>


In [20]:
print('맨 뒤의 값: ',array1[-1],'맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값:  9 맨 뒤에서 두번째 값: 8


In [21]:
array1[0]=0
array1[8]=0
print(array1)

[0 2 3 4 5 6 7 8 0]


In [22]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

print(array2d)

print("(row=0,col=0) index 가리키는 값:", array2d[0,0])
print("(row=0,col=1) index 가리키는 값:", array2d[0,1])
print("(row=1,col=0) index 가리키는 값:", array2d[1,0])
print("(row=2,col=2) index 가리키는 값:", array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


In [24]:
#26페이지
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array1)
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [26]:
#27페이지 슬라이싱
array1 = np.arange(1,10)
print(array1)

array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [29]:
#28페이지 2차원 슬라이싱
arr1d = np.arange(1,10)
arr2d = arr1d.reshape(3,3)
print('arr2d:\n', arr2d)

print("arr2d[0:2, 0:2]\n", arr2d[0:2, 0:2])
print("arr2d[1:3, 0:3]\n", arr2d[1:3, 0:3])
print("arr2d[1:3, :]\n", arr2d[1:3, :])
print("arr2d[:, :]\n", arr2d[:, :])
print("arr2d[:2, 1:]\n", arr2d[:2, 1:])
#col에만 슬라이싱, row는 단일값도 가능
print("arr2d[:2, 0]\n", arr2d[:2, 0])

arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[0:2, 0:2]
 [[1 2]
 [4 5]]
arr2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
arr2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
arr2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[:2, 1:]
 [[2 3]
 [5 6]]
arr2d[:2, 0]
 [1 4]


In [30]:
print(arr2d[0])
print(arr2d[1])
print(arr2d[0].shape, arr2d[1].shape)

[1 2 3]
[4 5 6]
(3,) (3,)


In [32]:
#30페이지
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print(array3.tolist(),"\n")

array4 = array2d[[0,1],0:2]
print(array4.tolist(),"\n")

array5 = array2d[[0,1]]
print(array5.tolist(),'\n')

[3, 6] 

[[1, 2], [4, 5]] 

[[1, 2, 3], [4, 5, 6]] 



In [33]:
array1d = np.arange(1,10)
#조건 적용
array3 = array1d[array1d>5]
print(array3)

[6 7 8 9]


In [34]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [37]:
original=np.array([3,1,9,5])

print(original)
print(np.sort(original))
print(original)
print(original.sort())
print(original)


[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [39]:
array2d = np.array([[8,12],
                  [7,1]])
print('원본:\n:', array2d)

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n:',sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('col 방향으로 정렬:\n:',sort_array2d_axis1)

원본:
: [[ 8 12]
 [ 7  1]]
로우 방향으로 정렬:
: [[ 7  1]
 [ 8 12]]
col 방향으로 정렬:
: [[ 8 12]
 [ 1  7]]


In [40]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:\n',sort_indices)
print('원본 행렬은 변하지 않았다:\n',org_array)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:
 [1 0 3 2]
원본 행렬은 변하지 않았다:
 [3 1 9 5]


In [41]:
#36페이지, 학생 이름과 시험 점수
name_array = np.array(['존','마이크','사라','케이트','사무엘'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스:\n:',sort_indices_asc)
#팬시 인덱스 적용
print('성적 오름차순으로 name_array의 이름 출력:\n',name_array[sort_indices_asc])

성적 오름차순 정렬시 score_array의 인덱스:
: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력:
 ['존' '사라' '사무엘' '마이크' '케이트']


In [42]:
A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
           [9,10],
           [11,12]])

dot_product = np.dot(A,B)

print(dot_product)

[[ 58  64]
 [139 154]]


In [44]:
A=np.array([[1,2],
           [3,4],
           [5,6]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3 5]
 [2 4 6]]
